### ISSUE TITLE
test failures - P11Object

### ISSUE THREAD

**Issue by vjardin** [gamringer/php-pkcs11#36]
Both following tests are failing on Ubuntu 20.04.1 with the head of SoftHSM2:

```
/home/vjardin/bin/bin/softhsm2-util -v
2.6.1
```
```
tests/0113-copy-object.sh          
object(Pkcs11\P11Object)#3 (0) {
}

Fatal error: Uncaught TypeError: Argument 1 passed to Pkcs11\Session::copyObject() must be an instance of Pkcs11\Object, instance of Pkcs11\P11Object given in php-pkcs11/tests/0113-copy-object.php:18
Stack trace:
#0 php-pkcs11/tests/0113-copy-object.php(18): Pkcs11\Session->copyObject(Object(Pkcs11\P11Object), Array)
#1 {main}
  thrown in php-pkcs11/tests/0113-copy-object.php on line 18
```
```
tests/0114-destroy-object.sh          
object(Pkcs11\P11Object)#3 (0) {
}
array(2) {
  [17]=>
  string(12) "Hello World!"
  [3]=>
  string(14) "Original Label"
}

Fatal error: Uncaught TypeError: Argument 1 passed to Pkcs11\Session::destroyObject() must be an instance of Pkcs11\Object, instance of Pkcs11\P11Object given in php-pkcs11/tests/0114-destroy-object.php:24
Stack trace:
#0 php-pkcs11/tests/0114-destroy-object.php(24): Pkcs11\Session->destroyObject(Object(Pkcs11\P11Object))
#1 {main}
  thrown in php-pkcs11/tests/0114-destroy-object.php on line 24
```

Currently, I could not find out why it "passes" with the CI.

**Comment by gamringer** [comment]
From what commit are you trying to run the tests ? I am having no issue.

**Comment by gamringer** [comment]
I made a few changes in a8d45e6dc4975be7599c2992765259fb615ec0cd. Is this working for you ?

**Comment by remicollet** [comment]
Same issue with 0.1.1

**Comment by vjardin** [comment]
Yes, it works, thank you. This issue can be closed.
